name: Generate snake

on:
  schedule:
    - cron: "00 22 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update snake grid
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: oHTGo
          svg_out_path: dist/snake.svg
      # Deploy to GitHub Pages
      - uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          # Don't Run this workflow on your default branch
          target_branch: snake
          commit_message: Update snake
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.SNAKE_PROFILE_TOKEN }}
